ARG VARIANT="bullseye-slim"
FROM debian:${VARIANT}

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install libssl-dev \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

COPY build/example/ritms_ott/ritms_ott /opt/up2date

WORKDIR /opt
ENTRYPOINT ["/opt/up2date"]
