ARG VARIANT="bullseye"
FROM debian:${VARIANT}

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install ca-certificates make cmake git curl zip unzip tar pkg-config build-essential libssl-dev \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

COPY build.sh /var/build.sh
RUN chmod +x /var/build.sh

ENTRYPOINT ["/var/build.sh"]